## SIB - P1

A Jupyter Notebook with examples of how to use the Dataset object.
18/09/2023

In [3]:
from si.data.dataset import Dataset
import numpy as np

# create a dataset
X = np.random.rand(150, 30)
y = np.random.randint(0, 2, 150)
dataset = Dataset(X, y)
dataset.shape()

(150, 30)

In [4]:
# get the X
dataset.X

array([[0.48254623, 0.46100338, 0.04560052, ..., 0.06923758, 0.3552377 ,
        0.19502147],
       [0.79970596, 0.31603694, 0.00425893, ..., 0.86494082, 0.67781223,
        0.828022  ],
       [0.85160726, 0.94452201, 0.54395141, ..., 0.52253934, 0.51366534,
        0.54659464],
       ...,
       [0.68226937, 0.63210503, 0.88468889, ..., 0.72362372, 0.98019431,
        0.01014813],
       [0.15385711, 0.84747179, 0.57017733, ..., 0.67081772, 0.9225559 ,
        0.82880839],
       [0.12673667, 0.28470413, 0.21177616, ..., 0.61696748, 0.9818951 ,
        0.86030784]])

In [5]:
#get the features names
dataset.features

['feat_0',
 'feat_1',
 'feat_2',
 'feat_3',
 'feat_4',
 'feat_5',
 'feat_6',
 'feat_7',
 'feat_8',
 'feat_9',
 'feat_10',
 'feat_11',
 'feat_12',
 'feat_13',
 'feat_14',
 'feat_15',
 'feat_16',
 'feat_17',
 'feat_18',
 'feat_19',
 'feat_20',
 'feat_21',
 'feat_22',
 'feat_23',
 'feat_24',
 'feat_25',
 'feat_26',
 'feat_27',
 'feat_28',
 'feat_29']

In [6]:
# has label?
dataset.has_label()

True

In [7]:
# print the label
dataset.y

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1])

In [8]:
# get classes
dataset.get_classes()

array([0, 1])

In [9]:
# statistics summary
dataset.summary()

feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
mean    0.515001  0.514826  0.510448  0.503927  0.507491  0.508385  0.490074   
median  0.547269  0.523150  0.505981  0.541904  0.519066  0.537136  0.454528   
min     0.000612  0.013276  0.002374  0.001066  0.000622  0.005766  0.003557   
max     0.990696  0.998693  0.997153  0.997390  0.975887  0.996499  0.985878   
var     0.080417  0.075746  0.084585  0.091679  0.080721  0.087515  0.081508   

          feat_7    feat_8    feat_9  ...   feat_20   feat_21   feat_22  \
mean    0.498109  0.492645  0.526283  ...  0.491665  0.480787  0.477713   
median  0.488742  0.476253  0.518664  ...  0.455381  0.498812  0.432046   
min     0.001812  0.002258  0.001121  ...  0.000632  0.011701  0.000905   
max     0.988984  0.996133  0.994291  ...  0.998980  0.998291  0.996283   
var     0.091288  0.091642  0.081013  ...  0.090880  0.093747  0.087158   

         feat_23   feat_24   feat_25   feat_26   feat_27   feat_28   feat_29  
mean    0.461867  0.496003  0.493743  0.503472  0.498431  0.497079  0.494804  
median  0.418562  0.551343  0.518620  0.511268  0.525527  0.494871  0.496943  
min     0.004858  0.001433  0.012035  0.004648  0.001565  0.000032  0.002236  
max     0.988296  0.997945  0.986549  0.999205  0.998271  0.997398  0.998206  
var     0.085754  0.083797  0.085982  0.086479  0.087713  0.084440  0.089499  

[5 rows x 30 columns]

In [10]:
from si.io.data_file import read_data_file

# read breast dataset from data file
breast_dataset = read_data_file('../datasets/breast_bin/breast-bin.data', sep=',', label=True)
breast_dataset.summary()

feat_0     feat_1     feat_2     feat_3     feat_4     feat_5  \
mean     4.417740   3.134478   3.207439   2.806867   3.216023   3.486409   
median   4.000000   1.000000   1.000000   1.000000   2.000000   1.000000   
min      1.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
max     10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
var      7.917053   9.298082   8.819630   8.141527   4.896110  13.099601   

           feat_6     feat_7     feat_8  
mean     3.437768   2.866953   1.589413  
median   3.000000   1.000000   1.000000  
min      1.000000   1.000000   1.000000  
max     10.000000  10.000000  10.000000  
var      5.937114   9.311340   2.937284

In [11]:
breast_dataset.y

array([1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0.

In [12]:
print('Features', breast_dataset.features)
print('Label', breast_dataset.label)

Features ['feat_0', 'feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', 'feat_6', 'feat_7', 'feat_8']
Label y


In [13]:
# write the same fila with a different name
from si.io.data_file import write_data_file
write_data_file('../datasets/breast_bin/breast-bin_tabular.tsv', breast_dataset, sep='\t', label=True)

In [14]:
from si.io.csv_file import read_csv

# read iris dataset from data file
iris_dataset = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
iris_dataset.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [15]:
iris_dataset.get_classes()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [16]:
# write the same file with a different name
from si.io.csv_file import write_csv
write_csv('../datasets/iris/iris_tabular.tsv', iris_dataset, sep='\t', features=True, label=True)

In [17]:
# random dataset
from si.data.dataset import Dataset
random_dataset = Dataset.from_random(150, 30, 4)
random_dataset.get_classes()

array([0, 1, 2, 3])

In [18]:
# from dataframe
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(150, 30))
df_dataset = Dataset.from_dataframe(df)
df_dataset.X

array([[0.57787157, 0.22685948, 0.50707519, ..., 0.97491821, 0.48020498,
        0.26292817],
       [0.70994981, 0.53527252, 0.2390533 , ..., 0.77913627, 0.10020917,
        0.9641101 ],
       [0.96586977, 0.75810858, 0.45532751, ..., 0.6951125 , 0.5614978 ,
        0.40151676],
       ...,
       [0.48660229, 0.38321858, 0.26553553, ..., 0.68971756, 0.13128254,
        0.25355093],
       [0.2129998 , 0.73703797, 0.22182435, ..., 0.37404596, 0.3506653 ,
        0.99248519],
       [0.54954742, 0.03010096, 0.40901583, ..., 0.00686506, 0.63986092,
        0.24672102]])

In [19]:
df_dataset.has_label()

False

In [20]:
df_w_nas = read_csv('../datasets/iris/iris_missing_data.csv', sep=',', features=True, label=True)
df_w_nas.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, nan, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, nan],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, nan, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [nan, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, nan],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, nan],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
from copy import copy

df1 = copy(df_w_nas).dropna()
df1.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3

In [22]:
df2 = copy(df_w_nas).fillna(0)
df2.X

ValueError: Value must be "mean", "median", or a float

In [ ]:
df2.remove_by_index(0)
df2.X