Exercise 1 - Dataset - Numpy Indexing and Slicing

In [1]:
import pandas as pd
import numpy as np 
from si.data.dataset import Dataset

1.1) In this exercise , we will use the iris dataset . Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).

In [2]:
from si.io.csv_file import read_csv
iris = read_csv("/Users/tiago_silva/Documents/GitHub/si/datasets/iris/iris.csv", sep=",", features=True, label=True)

iris.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

1.2) Select the penultimate independent variable . What is the dimension of the resulting array

In [3]:
resultP = iris.X[:, -2]
print(resultP.shape)
resultP

(150,)


array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

1.3) Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable feature?

In [4]:
resultL_10 = iris.X[-10:]
print(resultL_10.mean(axis=0))
resultL_10

[6.45 3.03 5.33 2.17]


array([[6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables features . How many samples do you obtain?

In [5]:
result_samples = iris.X[(iris.X <= 6).all(axis=1)]
print(result_samples.shape)
print(len(result_samples))
result_samples

(89, 4)
89


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

1.5) Select all samples with a class label different from 'Iris-setosa'. How many samples do you obtain?

In [6]:
resultsNotSetosa = iris.X[iris.y != 'Iris-setosa']
len(resultsNotSetosa)

100

2) Testing the added functions, dropna, fillna and remove by index

In [7]:
X = np.array([[1, 2, 3],[1, np.nan, 3],[1, 2, np.nan]])
y = np.array([0, 1, 0])

features = ['feature_1', 'feature_2', 'feature_3']
label = 'target'
dataset = Dataset(X, y, features, label)
dataset.X

array([[ 1.,  2.,  3.],
       [ 1., nan,  3.],
       [ 1.,  2., nan]])

In [8]:
X = np.array([[1, 2, 3],[1, np.nan, 3],[1, 2, np.nan]])
y = np.array([0, 1, 0])

features = ['feature_1', 'feature_2', 'feature_3']
label = 'target'
dataset = Dataset(X, y, features, label)

dataset_dropna = dataset.dropna()
dataset_dropna.X

array([[1., 2., 3.]])

In [9]:
X = np.array([[1, 2, 3],[1, np.nan, 3],[1, 2, np.nan]])
y = np.array([0, 1, 0])

features = ['feature_1', 'feature_2', 'feature_3']
label = 'target'
dataset = Dataset(X, y, features, label)

dataset_fillna_value = dataset.fillna(value=0)
dataset_fillna_value.X

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [10]:
X = np.array([[1, 2, 3],[1, np.nan, 3],[1, 2, np.nan]])
y = np.array([0, 1, 0])

features = ['feature_1', 'feature_2', 'feature_3']
label = 'target'
dataset = Dataset(X, y, features, label)

dataset_fillna_mean = dataset.fillna(value='mean')
dataset_fillna_mean.X

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [11]:
X = np.array([[1, 2, 3],[1, np.nan, 3],[1, 2, np.nan]])
y = np.array([0, 1, 0])

features = ['feature_1', 'feature_2', 'feature_3']
label = 'target'
dataset = Dataset(X, y, features, label)

dataset_fillna_median = dataset.fillna(value='median')
dataset_fillna_median.X

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [12]:
X = np.array([[1, 2, 3],[1, np.nan, 3],[1, 2, np.nan]])
y = np.array([0, 1, 0])

features = ['feature_1', 'feature_2', 'feature_3']
label = 'target'
dataset = Dataset(X, y, features, label)

dataset_remove_by_index = dataset.remove_by_index(index=1)
dataset_remove_by_index.X

array([[ 1.,  2.,  3.],
       [ 1.,  2., nan]])